name: NR Broker Vault login action
description: This action logins the service to Vault, so that automation can access the service's secrets.
branding:
  icon: package
  color: blue

inputs:
  action_token:
    description: The token of the action containing the service to use to login as
    required: true
  broker_url:
    default: https://nr-broker.apps.silver.devops.gov.bc.ca
    description: The broker url.
  role_id:
    description: The service's application role id in vault. Setting this is recommended to avoid environment mismatch.
    required: true
  vault_url:
    default: https://knox.io.nrs.gov.bc.ca
    description: The vault url.
  wrap_token:
    default: false
    description: >
      If the token should be returned wrapped. This must be set to true if the
      action will send the token to an external system.
runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    - id: broker-vault-login
      shell: bash
      env:
        ACTION_TOKEN: ${{ inputs.action_token }}
        BROKER_URL: ${{ inputs.broker_url }}
        PROVISION_ROLE_ID: ${{ inputs.role_id }}
        VAULT_URL: ${{ inputs.vault_url }}
        WRAP_TOKEN: ${{ inputs.wrap_token }}
      run: vault-login.sh
